### ISSUE TITLE
BTC green wallet not synchronizing

### ISSUE THREAD

**Issue by DartDan** [BTCgreen-Network/btcgreen-blockchain#26]
![btcgreen](https://user-images.githubusercontent.com/93547103/139723570-9a71b93e-5c51-40a3-965a-3a885c44c5d0.PNG)

It just spins and does not sync I left it like this for a few days and no change.

Can anyone help please

**Comment by BTCgreen-Network** [comment]
Download the db.rar folder included in the release and extract it and place the "blockchain_v1_mainnet.sqlite" and "peer_table_node.sqlite" files in your db folder located at "C:\Users\YOURPCNAME\.btcgreen\mainnet\db" Hope this solves your issue

**Comment by DartDan** [comment]
Thanks very much.
problem solved
